#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#


from os import listdir, sep
from random import randint
from subprocess import getoutput

user_folder = getoutput("echo $HOME")
wallpaper_folder = user_folder + sep + ".user_config/wallpapers"
wallpapers = listdir(wallpaper_folder)
selected_idx = randint(0, len(wallpapers)+1)
selected_wallpaper = wallpapers[selected_idx]

output = getoutput("rm {uf}/.wallpaper.jpg; ln -s {wf}/{selected} {uf}/.wallpaper.jpg".format(uf=user_folder, wf=wallpaper_folder, selected=selected_wallpaper))